---
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types
spec/spec_helper.rb:
  mock_with: ':rspec'
.github/workflows/ci.yml:
  pidfile_workaround: CentOS
spec/spec_helper_acceptance.rb:
  unmanaged: false
