name 'aboe-chrony'
version '0.0.1'
author 'aboe'
license 'Apache License, Version 2.0'
source 'git://github.com/aboe76/puppet-chrony.git'
project_page 'https://github.com/aboe76/puppet-chrony'
summary 'UKNOWN'
description 'Manage chrony daemon on Archlinux'
